/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class udpReader_PointCloudStitcher */

#ifndef _Included_udpReader_PointCloudStitcher
#define _Included_udpReader_PointCloudStitcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    icp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_icp
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    KinectData
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_KinectData
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    saveFrameFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_saveFrameFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    saveOutputCloud
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_saveOutputCloud
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    loadOutputCloud
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_loadOutputCloud
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    resetOutputCloud
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_resetOutputCloud
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    setInputOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_udpReader_PointCloudStitcher_setInputOutput
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    getPoints
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_udpReader_PointCloudStitcher_getPoints
  (JNIEnv *, jobject);

/*
 * Class:     udpReader_PointCloudStitcher
 * Method:    getInputPoints
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_udpReader_PointCloudStitcher_getInputPoints
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
